language: node_js
node_js: "6"

install: npm install

script: npm run generate

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $7d9c698df87148fdac6d594a8277d6a4bdebb406
  on:
    branch: master
